### ISSUE TITLE
Intellij won't start with this plugin installed

### ISSUE THREAD

**Issue by claudiobosticco** [turbanoff/RunConfigurationAsAction#17]
Intellij won't start with this plugin installed, here are the details of my installation:

IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 7000M
Cores: 12
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  debugger.watches.in.variables=false
  debugger.new.tool.window.layout=true
  search.everywhere.settings=true
  ide.experimental.ui=true
  terminal.new.ui=true
Non-Bundled Plugins:
  com.intellij.plugins.expui (0.4)
  com.github.b3er.idea.plugins.arc.browser (0.32)
  com.jetbrains.space (241.14494.150)
  Pythonid (241.14494.240)
  GrepConsole (12.25.0-IJ2023.3)
  net.seesharpsoft.intellij.plugins.csv (3.3.0-241)
  com.jetbrains.packagesearch.intellij-plugin (241.0.8)
  com.intellij.ml.llm (241.14494.240)
  com.intellij.plugins.html.instantEditing (241.14494.140)
Kotlin: 241.14494.240-IJ

**Comment by turbanoff** [comment]
Do you have any exceptions on the start? Can you please check IDEA logs. It's unlikely that this plugin is the reason.

**Comment by claudiobosticco** [comment]
Hello and thanks for your quick reply.

In the log, after start, I see only 3 occurrences of "org.turbanov", the relevant one may or may not be:

`		- "projectOpened component executing":StandaloneCoroutine{Active}, state: RUNNING [StartupAbortedExceptionHandler, projectOpened component executing, kotlinx.coroutines.UndispatchedMarker@34412bf6, com.intellij.platform.ide.diagnostic.startUpPerformanceReporter.FUSProjectHotStartUpMeasurer$MyMarker@45fd32dd, Dispatchers.EDT]
			at java.base@17.0.10/jdk.internal.misc.Unsafe.park(Native Method)
			at java.base@17.0.10/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
			at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:88)
			at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
			at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
			at com.intellij.serviceContainer.ComponentManagerImplKt$runBlockingInitialization$1.invoke(ComponentManagerImpl.kt:1636)
			at com.intellij.serviceContainer.ComponentManagerImplKt$runBlockingInitialization$1.invoke(ComponentManagerImpl.kt:1627)
			at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:83)
			at com.intellij.serviceContainer.ComponentManagerImplKt.runBlockingInitialization(ComponentManagerImpl.kt:1627)
			at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1547)
			at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:754)
			at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:698)
			at com.intellij.execution.RunManager$Companion.getInstance(RunManager.kt:27)
			at com.intellij.execution.RunManager.getInstance(RunManager.kt)
			at com.intellij.execution.RunManagerEx.getInstanceEx(RunManagerEx.java:17)
			at org.turbanov.actions.Bootstrap.projectOpened(Bootstrap.java:191)
			at com.intellij.openapi.project.impl.ProjectManagerImplKt$runInitProjectActivities$3$1$1.invoke(ProjectManagerImpl.kt:1010)
			at com.intellij.openapi.project.impl.ProjectManagerImplKt$runInitProjectActivities$3$1$1.invoke(ProjectManagerImpl.kt:1009)
			at com.intellij.openapi.progress.CoroutinesKt.blockingContextInner(coroutines.kt:320)
			at com.intellij.openapi.progress.CoroutinesKt.access$blockingContextInner(coroutines.kt:1)
			at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invokeSuspend(coroutines.kt:197)
			at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
			at com.intellij.openapi.progress.CoroutinesKt$blockingContext$2.invoke(coroutines.kt)
			at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
			at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
			at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:196)
			at com.intellij.openapi.project.impl.ProjectManagerImplKt$runInitProjectActivities$3.invokeSuspend(ProjectManagerImpl.kt:1009)
			- BlockingCoroutine{Active}, state: SUSPENDED [com.intellij.openapi.progress.RunBlockingUnderReadActionMarker@69ddc0cc, NestedBlockingEventLoop@71cb01cf]
				at com.intellij.serviceContainer.ComponentManagerImplKt$getOrCreateInstanceBlocking$3.invokeSuspend(ComponentManagerImpl.kt:1548)
`
[idea copia.log](https://github.com/turbanoff/RunConfigurationAsAction/files/14887244/idea.copia.log)

**Comment by turbanoff** [comment]
Thank you for the log.
Looks like IDEA issue. Reported - https://youtrack.jetbrains.com/issue/IDEA-350878/Intellij-wont-start-with-RunConfigurationAsAction-plugin-installed
Let's see, what JB answers

**Comment by claudiobosticco** [comment]
starred, thank you very much

**Comment by turbanoff** [comment]
I've uploaded a new version of the plugin - https://github.com/turbanoff/RunConfigurationAsAction/releases/download/3.0/RunConfigurationAsAction-3.0.jar
Please try.

Uploaded to JetBrains marketplace too. Will be available there after their approval.

**Comment by claudiobosticco** [comment]
I can confirm that it's working for me, thank you very much!
